let order = {
    "success": true,
    "results": {
        "shipmentLevel": {
            "30953514": [
                {
                    "orderId": 181954703,
                    "shipmentId": 30953514,
                    "shipmentNumber": "45324194",
                    "returnId": 0,
                    "returnData": {},
                    "orderItemId": 6002795006,
                    "shipNode": "21597",
                    "ShippedQuantity": 1,
                    "trackingNumber": "435803746",
                    "invoiceNumber": "2159701I25000732",
                    "carrierPickedDate": "2025-05-27T13:15:11.000Z",
                    "deliveredDate": "2025-05-27T14:04:10.000Z",
                    "statusName": "Delivered",
                    "groupbystatus": "Delivered",
                    "groupbystatusmessage": "Yay! Delivered Successfully!",
                    "createdDate": "2025-05-27T09:40:08.000Z",
                    "returnAvailableFromDate": "2025-05-27",
                    "returnAvailableTillDate": "2025-06-11",
                    "trackingUrl": "https://track.vanheusenindia.com/?waybill=",
                    "cp_key": "9c4e442e-870e-463b-9930-bb83c4df2fdf",
                    "sku": "8905813083566",
                    "ndrNprCode": null,
                    "ndrNprDisplayMessage": null,
                    "ndrNprDescription": null,
                    "cpReturnUrl": "https://peterengland.clickpost.in/returns?waybill=435803746&security_key=9c4e442e-870e-463b-9930-bb83c4df2fdf&sku=8905813083566&app_only=true"
                }
            ]
        },
        "orderLevel": [
            {
                "OrderId": 181954703,
                "id_shop": 6,
                "orderNo": "SA181954703",
                "brandname": "Van Heusen",
                "id_store": 21597,
                "ColorName": "Brown",
                "Sizes": [
                    {
                        "IsDefault": 0,
                        "HSN": "62033990",
                        "Discount": {
                            "StartDate": "2025-05-24T19:30:00",
                            "Type": "percentage",
                            "DealType": "",
                            "Amount": 30,
                            "EndDate": "2025-05-29T23:59:59"
                        },
                        "ArticleCode": "0",
                        "StoreIds": "21597,25746,26309,28249",
                        "Reference": "VHBZISLF206788_VHBZISLF206788_36",
                        "Quantity": 2,
                        "Sequence": 101,
                        "SellerIds": "ABFRL",
                        "Name": "36",
                        "SellingPrice": "5599.00",
                        "EAN": "8905813083559",
                        "Price": "7999.00",
                        "OfflineQuantity": 0,
                        "SafetyFactor": 0,
                        "TaxClassificationOnArt": 1,
                        "ID": 5172394,
                        "DollarPrice": "0.00",
                        "enable": 1
                    },
                    {
                        "IsDefault": 0,
                        "HSN": "62033990",
                        "Discount": {
                            "StartDate": "2025-05-24T19:30:00",
                            "Type": "percentage",
                            "DealType": "",
                            "Amount": 30,
                            "EndDate": "2025-05-29T23:59:59"
                        },
                        "ArticleCode": "0",
                        "StoreIds": "21597,27007,27010,27208,27612,28216,28249,29763",
                        "Reference": "VHBZISLF206788_VHBZISLF206788_38",
                        "Quantity": 15,
                        "Sequence": 103,
                        "SellerIds": "ABFRL",
                        "Name": "38",
                        "SellingPrice": "5599.00",
                        "EAN": "8905813083566",
                        "Price": "7999.00",
                        "OfflineQuantity": 0,
                        "SafetyFactor": 0,
                        "TaxClassificationOnArt": 1,
                        "ID": 5172395,
                        "DollarPrice": "0.00",
                        "ProductDiscountFlag": 0,
                        "previousDiscount": {
                            "Type": "percentage",
                            "Amount": "30.00"
                        },
                        "enable": 1
                    },
                    {
                        "IsDefault": 1,
                        "HSN": "62033990",
                        "Discount": {
                            "StartDate": "2025-05-24T19:30:00",
                            "Type": "percentage",
                            "DealType": "",
                            "Amount": 30,
                            "EndDate": "2025-05-29T23:59:59"
                        },
                        "ArticleCode": "0",
                        "StoreIds": "25966,27027,27603,28136,28165,28216,28249,29763",
                        "Reference": "VHBZISLF206788_VHBZISLF206788_40",
                        "Quantity": 12,
                        "Sequence": 105,
                        "SellerIds": "ABFRL",
                        "Name": "40",
                        "SellingPrice": "5599.00",
                        "EAN": "8905610705319",
                        "Price": "7999.00",
                        "OfflineQuantity": 0,
                        "SafetyFactor": 0,
                        "TaxClassificationOnArt": 1,
                        "ID": 5172393,
                        "DollarPrice": "0.00",
                        "enable": 1
                    },
                    {
                        "IsDefault": 0,
                        "HSN": "62033990",
                        "Discount": {
                            "StartDate": "2025-05-24T19:30:00",
                            "Type": "percentage",
                            "DealType": "",
                            "Amount": 30,
                            "EndDate": "2025-05-29T23:59:59"
                        },
                        "ArticleCode": "0",
                        "StoreIds": "21597,25966,27007,27010,28111,28165",
                        "Reference": "VHBZISLF206788_VHBZISLF206788_42",
                        "Quantity": 6,
                        "Sequence": 107,
                        "SellerIds": "ABFRL",
                        "Name": "42",
                        "SellingPrice": "5599.00",
                        "EAN": "8905813083573",
                        "Price": "7999.00",
                        "OfflineQuantity": 0,
                        "SafetyFactor": 0,
                        "TaxClassificationOnArt": 1,
                        "ID": 5172396,
                        "DollarPrice": "0.00",
                        "enable": 1
                    },
                    {
                        "IsDefault": 0,
                        "HSN": "62033990",
                        "Discount": {
                            "StartDate": "2025-05-24T19:30:00",
                            "Type": "percentage",
                            "DealType": "",
                            "Amount": 30,
                            "EndDate": "2025-05-29T23:59:59"
                        },
                        "ArticleCode": "0",
                        "StoreIds": "21597",
                        "Reference": "VHBZISLF206788_VHBZISLF206788_44",
                        "Quantity": 0,
                        "Sequence": 109,
                        "SellerIds": "ABFRL",
                        "Name": "44",
                        "SellingPrice": "5599.00",
                        "EAN": "8905813083580",
                        "Price": "7999.00",
                        "OfflineQuantity": 0,
                        "SafetyFactor": 0,
                        "TaxClassificationOnArt": 1,
                        "ID": 5172397,
                        "DollarPrice": "0.00",
                        "enable": 0
                    },
                    {
                        "IsDefault": 0,
                        "HSN": "62033990",
                        "Discount": {
                            "StartDate": "2025-05-24T19:30:00",
                            "Type": "percentage",
                            "DealType": "",
                            "Amount": 30,
                            "EndDate": "2025-05-29T23:59:59"
                        },
                        "ArticleCode": "0",
                        "StoreIds": null,
                        "Reference": "VHBZISLF206788_VHBZISLF206788_46",
                        "Quantity": 0,
                        "Sequence": 110,
                        "SellerIds": "0,ABFRL",
                        "Name": "46",
                        "SellingPrice": "5599.00",
                        "EAN": "8905813083597",
                        "Price": "7999.00",
                        "OfflineQuantity": 0,
                        "SafetyFactor": 0,
                        "TaxClassificationOnArt": 1,
                        "ID": 5172398,
                        "DollarPrice": "0.00",
                        "enable": 0
                    },
                    {
                        "IsDefault": 0,
                        "HSN": "62033990",
                        "Discount": {
                            "StartDate": "2025-05-24T19:30:00",
                            "Type": "percentage",
                            "DealType": "",
                            "Amount": 30,
                            "EndDate": "2025-05-29T23:59:59"
                        },
                        "ArticleCode": "0",
                        "StoreIds": null,
                        "Reference": "VHBZISLF206788_VHBZISLF206788_48",
                        "Quantity": 0,
                        "Sequence": 111,
                        "SellerIds": "0,ABFRL",
                        "Name": "48",
                        "SellingPrice": "5599.00",
                        "EAN": "8905813083603",
                        "Price": "7999.00",
                        "OfflineQuantity": 0,
                        "SafetyFactor": 0,
                        "TaxClassificationOnArt": 1,
                        "ID": 5172399,
                        "DollarPrice": "0.00",
                        "enable": 0
                    }
                ],
                "ParentCategoryName": "Blazers",
                "IsAccessories": false,
                "personalisation": "",
                "Subbrand": "Van Heusen",
                "TagLoop": 1,
                "linkrewrite": "men-brown-textured-slim-fit-formal-blazer",
                "productCategory": "Formal Blazers_Men",
                "productPattern": "Textured",
                "productCollar": "",
                "productCollection": "Formal",
                "productFit": "Slim Fit",
                "productMaterial": "57% Rayon, 38% Polyester and 5% Elastane",
                "productStyleId": "VHBZISLF206788",
                "ProductDiscountFlag": 0,
                "productIdAttr": 5172395,
                "reductionAmount": "0.000000",
                "reductionPercentage": "30.00",
                "GenderName": "Men",
                "isHyperlocalOrder": 1,
                "orderItemId": 6002795006,
                "cancelledDate": null,
                "refundedDate": null,
                "cancelInitiated": 0,
                "cancel_status": false,
                "productReferance": "VHBZISLF206788_VHBZISLF206788_38",
                "paymentMode": "FREE ORDER",
                "module": "freeorder",
                "orderPlacedDate": "2025-05-27T09:27:30.000Z",
                "productId": 905903,
                "productEAN": "8905813083566",
                "ProductName": "Men Brown Textured Slim Fit Formal Blazer",
                "reviewid": 204310,
                "reviewrating": 5,
                "totalPaid": "0.00",
                "totalPrice": "279.00",
                "netPrice": "0.00",
                "unitPrice": "5599.00",
                "originalPrice": "7999.00",
                "sellingprice": "5599.00",
                "productDiscountpercentage": "30.00",
                "expectedDeliveryDate": "2025-05-28T09:27:30.000Z",
                "shipmentDelayedMsg": "",
                "productQuantity": 1,
                "discountPercent": "30.00",
                "discountAmount": "0.00",
                "orderCurrentStatus": 5,
                "orderStatus": "Delivered",
                "groupbystatus": "Delivered",
                "groupbystatusmessage": "Yay! Delivered Successfully!",
                "cancelFailed": false,
                "offerName": "VHTEST95",
                "offerValue": "5320.00",
                "offerId": 11910766,
                "offerTypeId": 48,
                "offerTypeName": "Promotions On Cart Value",
                "myfitProduct": 0,
                "orderType": "",
                "isReturnable": 1,
                "totalProductDiscount": "2400.00",
                "discountPerPiece": "2400.00",
                "appliedOffers": [
                    {
                        "offerName": "Van Heusen Credits",
                        "discountAmount": "279.00"
                    },
                    {
                        "offerName": "Promotions",
                        "discountAmount": "5320.00"
                    }
                ],
                "orderHistory": [
                    {
                        "id_order": 181954703,
                        "id_order_state": 5,
                        "date_add": "2025-05-27T14:04:10.000Z",
                        "name": "Delivered"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 34,
                        "date_add": "2025-05-27T13:15:10.000Z",
                        "name": "Carrier Picked"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 76,
                        "date_add": "2025-05-27T11:45:16.000Z",
                        "name": "Shipped LSP Assigned"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 49,
                        "date_add": "2025-05-27T11:42:20.000Z",
                        "name": "Shipped"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 29,
                        "date_add": "2025-05-27T09:52:47.000Z",
                        "name": "Acknowledged"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 39,
                        "date_add": "2025-05-27T09:36:36.000Z",
                        "name": "Scheduled"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 28,
                        "date_add": "2025-05-27T09:36:11.000Z",
                        "name": "Created"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 3,
                        "date_add": "2025-05-27T09:34:36.000Z",
                        "name": "Preparation in progress"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 20,
                        "date_add": "2025-05-27T09:27:30.000Z",
                        "name": "On Hold"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 14,
                        "date_add": "2025-05-27T09:27:27.000Z",
                        "name": "Payment Pending"
                    },
                    {
                        "id_order": 181954703,
                        "id_order_state": 200,
                        "date_add": "2025-05-27T09:27:23.000Z",
                        "name": "Pending"
                    }
                ],
                "refundTypeFlag": 0,
                "imagePath": "https://assets.abfrlcdn.com/img/app/product/9/905903-11156679.jpg",
                "size": " 38",
                "stylecode": "VHBZISLF206788",
                "creditDiscount": 279,
                "loyaltyDiscount": "0.00",
                "egvDiscount": "0.00",
                "couponDiscount": 5320,
                "monogram_initials": "",
                "monogram_style": "",
                "monogram_font": "",
                "monogram_color": "",
                "monogram_placement": "",
                "monogram_imageurl": "",
                "couponDiscountPerPiece": "5320.00",
                "creditDiscountPerPiece": "279.00",
                "loyaltyDiscountPerPiece": 0,
                "egvDiscountPerPiece": 0,
                "shipmentId": 30953514,
                "ShippedQuantity": 1,
                "shipmentData": {
                    "orderId": 181954703,
                    "shipmentId": 30953514,
                    "shipmentNumber": "45324194",
                    "orderItemId": 6002795006,
                    "shipNode": "21597",
                    "trackingNumber": "435803746",
                    "invoiceNumber": "2159701I25000732",
                    "carrierPickedDate": "2025-05-27T13:15:11.000Z",
                    "deliveredDate": "2025-05-27T14:04:10.000Z",
                    "statusName": "Delivered",
                    "createdDate": "2025-05-27T09:40:08.000Z",
                    "returnAvailableFromDate": "2025-05-27",
                    "returnAvailableTillDate": "2025-06-11",
                    "trackingUrl": "https://track.vanheusenindia.com/?waybill=",
                    "cp_key": "9c4e442e-870e-463b-9930-bb83c4df2fdf",
                    "sku": "8905813083566",
                    "ndrNprCode": null,
                    "ndrNprDisplayMessage": null,
                    "ndrNprDescription": null,
                    "shipmentStatusId": 5,
                    "ShippedQuantity": 1,
                    "status": "Delivered"
                },
                "returnId": 0,
                "returnData": {},
                "uniqueId": "181954703-6002795006-30953514-0-5-1",
                "uniqueIdformat": "orderId-orderItemId-shipmentId-rmaId-status-index",
                "priceUniqueId": "5320.00-279.00-0-0",
                "priceUniqueIdFormat": "couponDiscountPerPiece-creditDiscountPerPiece-loyaltyDiscountPerPiece-egvDiscountPerPiece",
                "orderStatusMsg": "",
                "exchangeenabled": 1,
                "exchangeCreated": 0,
                "exchangeChildOrderNumber": "",
                "refundUtrNumber": "",
                "refundExpectedDate": ""
            }
        ],
        "deliveredAddressAndExpectedDeliveryDate": [
            {
                "addressId": 6764419,
                "addressFirstName": "Nagaraj ",
                "addressLastName": "tagloop",
                "deliveryMode": "",
                "address1": "ABFRL office , Divyanshree tech park",
                "address2": "Bangalore",
                "address3": "",
                "address4": "",
                "cityName": "Bangalore",
                "stateName": "Karnataka",
                "countryName": "India",
                "addressPincode": "560037",
                "expectedDeliveryDate": "2025-05-31T09:27:30.000Z",
                "mobileNumber": "9980008625",
                "shipmentDelayedMsg": ""
            }
        ],
        "personalizationDeliveryDate": [
            {
                "addressId": 6764419,
                "addressFirstName": "Nagaraj ",
                "addressLastName": "tagloop",
                "deliveryMode": "",
                "address1": "ABFRL office , Divyanshree tech park",
                "address2": "Bangalore",
                "address3": "",
                "address4": "",
                "cityName": "Bangalore",
                "stateName": "Karnataka",
                "countryName": "India",
                "addressPincode": "560037",
                "expectedDeliveryDate": "2025-06-02T09:27:30.000Z",
                "mobileNumber": "9980008625",
                "shipmentDelayedMsg": ""
            }
        ],
        "storeExpectedDeliveryDate": [
            {
                "21597": [
                    {
                        "addressId": 6764419,
                        "addressFirstName": "Nagaraj ",
                        "addressLastName": "tagloop",
                        "deliveryMode": "",
                        "address1": "ABFRL office , Divyanshree tech park",
                        "address2": "Bangalore",
                        "address3": "",
                        "address4": "",
                        "cityName": "Bangalore",
                        "stateName": "Karnataka",
                        "countryName": "India",
                        "addressPincode": "560037",
                        "expectedDeliveryDate": "2025-05-28T18:30:00.000Z",
                        "mobileNumber": "9980008625",
                        "shipmentDelayedMsg": "Shipment Delayed"
                    }
                ]
            }
        ],
        "reviewId": 204310,
        "reviewrating": 5
    },
    "msg": "",
    "cache": 0,
    "ttl": 0,
    "hash": "3c365423b47cac7701762de22943f225.5f1ff3b6447fd9e2788b89de4be87cf2"
}